platform :ios, '9.0'

target 'Expo' do

  pod 'KKDuktape', '~> 1.0'

  eval(IO.read('PodfileFragments/React.rb'), binding)

  post_install do |installer|
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        target.build_settings(config.name)['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = 'YES'
      end
    end
  end

  target 'ExpoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExpoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
